[package]
name = "lsusb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9.3"
owo-colors = "3.5.0"
prettytable-rs = "0.10.0" 
usb-ids = "1.2023.6"
